### ISSUE TITLE
Apparently hangouts bot only works for Gsuite customers

### ISSUE THREAD

**Issue by readeral** [lexoyo/node-red-contrib-hangouts-chat#1]
[As per this issue](https://github.com/googlecodelabs/hangouts-chat-apps-script/issues/7) it appears the hangout bot doesn't work for regular gmail accounts.

Is that your experience? Do you have a G Suite account?

**Comment by readeral** [comment]
Confirmed here: https://github.com/gsuitedevs/hangouts-chat-samples

Might be worth popping into your docs

**Comment by lexoyo** [comment]
Yes it is only for paid GSuite customers
I thought I wrote in the readme but I was mistaken, thank you for the report, I will add it

**Comment by lexoyo** [comment]
Done
Let me know if it is still not clear
Thx
